spring.application.name=JavaSpringGame

spring.datasource.url=jdbc:postgresql://localhost:5432/javagame
spring.datasource.password=postgres
spring.datasource.username=admin

spring.jpa.hibernate.ddl-auto=validate